2.1 capability
oasis-open/cti-stix-slider pull request #38
Opened 2018-11-20 02:34 UTC by rpiazza

make slider work with base visitor from pattern-validator

2018-11-27 19:14 UTC, clenk requested changes
Looking good. Just a few comments to look at, and there's some style issues to fix (I re-ran Travis since we made a new pattern-validator release).

2018-11-27 19:14 UTC, clenk commented on stix2slider/convert_stix.py
>          # bug in python_stix prevents using next line of code
Is this bug in the python_stix issue tracker? Should we prioritize fixing it?

2018-11-27 19:14 UTC, clenk commented on stix2slider/convert_stix.py
> +        types = convert_open_vocabs_to_controlled_vocabs(malware2x["malware_type"], MALWARE_LABELS_MAP)
Should be `malware_types`, plural.

2018-11-27 19:14 UTC, clenk commented on stix2slider/convert_stix.py
> +        source_1x_obj.information_source
Is there something missing from this line, or is it unnecessary?

2018-11-27 19:14 UTC, clenk commented on stix2slider/test/test_idioms.py
> +    version = os.environ['VERSION']
Maybe we should use a more specific name for the environment variable. Also, we should configure Tox to set this variable with both versions to make sure we test everything.

2018-11-27 19:16 UTC, rpiazza commented on stix2slider/convert_stix.py
> +        types = convert_open_vocabs_to_controlled_vocabs(malware2x["malware_type"], MALWARE_LABELS_MAP)
Good catch

2018-11-27 21:04 UTC, rpiazza commented on stix2slider/convert_stix.py
>          # bug in python_stix prevents using next line of code
see python cybox tracker #310.  The fix apparently didn't make it back to the slider.

2018-11-27 21:08 UTC, rpiazza commented on stix2slider/convert_stix.py
>          # bug in python_stix prevents using next line of code
see #39

2019-01-10 16:51 UTC, clenk approved these changes

2019-01-11 16:54 UTC, rpiazza commented
@clenk 

If you review latest changes and merge this - I can do the release.

2019-01-11 20:52 UTC, clenk approved these changes
Looks good, thanks @rpiazza!

2019-01-11 20:52 UTC, merged